### ISSUE TITLE
Unused import 

### ISSUE THREAD

**Issue by zoey-t** [soundxyz/sound-protocol#252]
Just start reading and studying the contracts, I have a question about the `SoundCreatorV1` contract. It imports the `UUPSUpgradeable` but I couldn't find where it's used. Was it used somewhere but I missed it or it's placed here for some specific reason?

**Comment by vigneshka** [comment]
Hey @zoey-t , thanks for flagging! It was a remnant of a previous iteration. It is not used anywhere and we will remove it.

**Comment by gigamesh** [comment]
thank you @zoey-t 
https://github.com/soundxyz/sound-protocol/pull/255
