### ISSUE TITLE
Compatibility with Polygon chain - Polygonscan verification

### ISSUE THREAD

**Issue by ander-db** [soundxyz/sound-protocol#280]
I've been trying to verify an _smartcontract_ deployed with the sample deploy script but constantly getting cloudflare block. I'm waiting the response of polygonscan and foundry technicall support to verify if is a problem related to them.

Even so, I wanted to ask here. Is there any know issue related to the verification of the smartcontract on Polygonscan?

There is no metion to Polygon anywhere on this repo and I'm not sure if there is any problem with it.

Thanks.

**Comment by gigamesh** [comment]
We've never deployed the protocol on Polygon so I'm not sure we can help with this

**Comment by ander-db** [comment]
Thanks for answering! Doesn't look to be a problem with this project. 
However you've never deployed the protocol on Polygon because _sound.xyz_ only focus on Ethereum? I ask this because surely we are going to implement it in Polygon (we will add all the necessary scripts and configurations), and we don't know if the managers of this project would want to add those functionalities.

**Comment by Vectorized** [comment]
Try compiling the contracts and running the scripts on a AWS or DigitalOcean server.

**Comment by ander-db** [comment]
I didn't recive any response from polygonscan.io, but I managed to verify it using the option _flatten_ from _forge_ and verifying it by hand on the website. It's a _polygonscan_ issue, so I'm closing this. Thanks for the support!
