### ISSUE TITLE
Missconfigured goerli smartcontracts addresses json

### ISSUE THREAD

**Issue by ander-db** [soundxyz/sound-protocol#281]
Those address are missconfigured to the `FixedPriceSignatureMinter`'s address instead of the correct ones:

https://github.com/soundxyz/sound-protocol/blob/cd8c86cbfd7b1f2436393b3c09dcd1977615ecc1/src/json/goerli.json#L5-L6

I'm openning a pull request to solve it.

**Comment by gigamesh** [comment]
thank you! https://github.com/soundxyz/sound-protocol/pull/282
